
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "IDENTIFIER REGEX RELATION\n    SubNode : ModNode\n            | ModNode RelationDisj\n            | '(' SubNode ')' \n            | '(' SubNode ')' RelationDisj\n    \n    RelationDisj : RelationConj\n                 | RelationConj '|' RelationDisj\n    \n    RelationConj : ModRelation\n                 | ModRelation RelationConj\n                 | ModRelation '&' RelationConj\n    \n    ModRelation : RelChild\n    \n    RelChild : Relation\n    \n    Relation : RELATION '{' Attributes '}' Relation_Next\n    \n    Relation_Next : ModNode\n                  | '(' SubNode ')'\n    \n    ModNode : Child\n    \n    Child : Description\n    \n    Description : '{' Attributes '}'\n                | '{' Attributes '}' '=' IDENTIFIER\n    \n    Attributes : IDENTIFIER ':' REGEX\n               | IDENTIFIER ':' REGEX ',' Attributes\n               | empty\n    empty :"
    
_lr_action_items = {'(':([0,3,30,35,],[3,3,35,3,]),'{':([0,3,12,30,35,],[6,6,20,6,6,]),'$end':([1,2,4,5,7,8,9,10,11,18,21,22,24,25,27,31,33,34,38,],[0,-1,-15,-16,-2,-5,-7,-10,-11,-8,-3,-17,-6,-9,-4,-18,-12,-13,-14,]),')':([2,4,5,7,8,9,10,11,13,18,21,22,24,25,27,31,33,34,37,38,],[-1,-15,-16,-2,-5,-7,-10,-11,21,-8,-3,-17,-6,-9,-4,-18,-12,-13,38,-14,]),'RELATION':([2,4,5,9,10,11,17,19,21,22,31,33,34,38,],[12,-15,-16,12,-10,-11,12,12,12,-17,-18,-12,-13,-14,]),'&':([4,5,9,10,11,22,31,33,34,38,],[-15,-16,19,-10,-11,-17,-18,-12,-13,-14,]),'|':([4,5,8,9,10,11,18,22,25,31,33,34,38,],[-15,-16,17,-7,-10,-11,-8,-17,-9,-18,-12,-13,-14,]),'IDENTIFIER':([6,20,28,32,],[15,15,31,15,]),'}':([6,14,16,20,26,29,32,36,],[-22,22,-21,-22,30,-19,-22,-20,]),':':([15,],[23,]),'=':([22,],[28,]),'REGEX':([23,],[29,]),',':([29,],[32,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'SubNode':([0,3,35,],[1,13,37,]),'ModNode':([0,3,30,35,],[2,2,34,2,]),'Child':([0,3,30,35,],[4,4,4,4,]),'Description':([0,3,30,35,],[5,5,5,5,]),'RelationDisj':([2,17,21,],[7,24,27,]),'RelationConj':([2,9,17,19,21,],[8,18,8,25,8,]),'ModRelation':([2,9,17,19,21,],[9,9,9,9,9,]),'RelChild':([2,9,17,19,21,],[10,10,10,10,10,]),'Relation':([2,9,17,19,21,],[11,11,11,11,11,]),'Attributes':([6,20,32,],[14,26,36,]),'empty':([6,20,32,],[16,16,16,]),'Relation_Next':([30,],[33,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> SubNode","S'",1,None,None,None),
  ('SubNode -> ModNode','SubNode',1,'p_SubNode','parser.py',78),
  ('SubNode -> ModNode RelationDisj','SubNode',2,'p_SubNode','parser.py',79),
  ('SubNode -> ( SubNode )','SubNode',3,'p_SubNode','parser.py',80),
  ('SubNode -> ( SubNode ) RelationDisj','SubNode',4,'p_SubNode','parser.py',81),
  ('RelationDisj -> RelationConj','RelationDisj',1,'p_RelationDisj','parser.py',127),
  ('RelationDisj -> RelationConj | RelationDisj','RelationDisj',3,'p_RelationDisj','parser.py',128),
  ('RelationConj -> ModRelation','RelationConj',1,'p_RelationConj','parser.py',142),
  ('RelationConj -> ModRelation RelationConj','RelationConj',2,'p_RelationConj','parser.py',143),
  ('RelationConj -> ModRelation & RelationConj','RelationConj',3,'p_RelationConj','parser.py',144),
  ('ModRelation -> RelChild','ModRelation',1,'p_ModRelation','parser.py',157),
  ('RelChild -> Relation','RelChild',1,'p_RelChild','parser.py',164),
  ('Relation -> RELATION { Attributes } Relation_Next','Relation',5,'p_Relation','parser.py',171),
  ('Relation_Next -> ModNode','Relation_Next',1,'p_Relation_Next','parser.py',182),
  ('Relation_Next -> ( SubNode )','Relation_Next',3,'p_Relation_Next','parser.py',183),
  ('ModNode -> Child','ModNode',1,'p_ModNode','parser.py',193),
  ('Child -> Description','Child',1,'p_Child','parser.py',200),
  ('Description -> { Attributes }','Description',3,'p_Description','parser.py',207),
  ('Description -> { Attributes } = IDENTIFIER','Description',5,'p_Description','parser.py',208),
  ('Attributes -> IDENTIFIER : REGEX','Attributes',3,'p_Attributes','parser.py',217),
  ('Attributes -> IDENTIFIER : REGEX , Attributes','Attributes',5,'p_Attributes','parser.py',218),
  ('Attributes -> empty','Attributes',1,'p_Attributes','parser.py',219),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',231),
]
