
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "RELATION IDENTIFIER REGEX\n    SubNode : ModNode\n            | ModNode RelationDisj\n            | '(' SubNode ')' \n            | '(' SubNode ')' RelationDisj\n    \n    RelationDisj : RelationConj\n                 | RelationConj '|' RelationDisj\n    \n    RelationConj : ModRelation\n                 | ModRelation RelationConj\n                 | ModRelation '&' RelationConj\n    \n    ModRelation : RelChild\n    \n    RelChild : Relation\n    \n    Relation : RELATION '{' Attributes '}' Relation_Next\n    \n    Relation_Next : ModNode\n                  | '(' SubNode ')'\n    \n    ModNode : Child\n    \n    Child : Description\n    \n    Description : '{' Attributes '}'\n                | '{' Attributes '}' '=' IDENTIFIER\n    \n    Attributes : IDENTIFIER ':' REGEX\n               | IDENTIFIER ':' REGEX ',' Attributes\n               | empty\n    empty :"
    
_lr_action_items = {'REGEX':([23,],[29,]),':':([15,],[23,]),'&':([1,4,8,10,11,22,31,33,35,38,],[-16,-15,18,-10,-11,-17,-18,-12,-13,-14,]),')':([1,3,4,7,8,9,10,11,12,17,19,22,24,25,26,31,33,35,37,38,],[-16,-1,-15,17,-7,-2,-10,-11,-5,-3,-8,-17,-4,-9,-6,-18,-12,-13,38,-14,]),'(':([0,2,30,34,],[2,2,34,2,]),'=':([22,],[28,]),',':([29,],[32,]),'RELATION':([1,3,4,8,10,11,17,18,20,22,31,33,35,38,],[-16,13,-15,13,-10,-11,13,13,13,-17,-18,-12,-13,-14,]),'{':([0,2,13,30,34,],[5,5,21,5,5,]),'IDENTIFIER':([5,21,28,32,],[15,15,31,15,]),'}':([5,14,16,21,27,29,32,36,],[-22,22,-21,-22,30,-19,-22,-20,]),'|':([1,4,8,10,11,12,19,22,25,31,33,35,38,],[-16,-15,-7,-10,-11,20,-8,-17,-9,-18,-12,-13,-14,]),'$end':([1,3,4,6,8,9,10,11,12,17,19,22,24,25,26,31,33,35,38,],[-16,-1,-15,0,-7,-2,-10,-11,-5,-3,-8,-17,-4,-9,-6,-18,-12,-13,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Description':([0,2,30,34,],[1,1,1,1,]),'ModRelation':([3,8,17,18,20,],[8,8,8,8,8,]),'RelationDisj':([3,17,20,],[9,24,26,]),'RelChild':([3,8,17,18,20,],[10,10,10,10,10,]),'Child':([0,2,30,34,],[4,4,4,4,]),'Relation':([3,8,17,18,20,],[11,11,11,11,11,]),'RelationConj':([3,8,17,18,20,],[12,19,12,25,12,]),'ModNode':([0,2,30,34,],[3,3,35,3,]),'Attributes':([5,21,32,],[14,27,36,]),'Relation_Next':([30,],[33,]),'SubNode':([0,2,34,],[6,7,37,]),'empty':([5,21,32,],[16,16,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> SubNode","S'",1,None,None,None),
  ('SubNode -> ModNode','SubNode',1,'p_SubNode','parser.py',78),
  ('SubNode -> ModNode RelationDisj','SubNode',2,'p_SubNode','parser.py',79),
  ('SubNode -> ( SubNode )','SubNode',3,'p_SubNode','parser.py',80),
  ('SubNode -> ( SubNode ) RelationDisj','SubNode',4,'p_SubNode','parser.py',81),
  ('RelationDisj -> RelationConj','RelationDisj',1,'p_RelationDisj','parser.py',127),
  ('RelationDisj -> RelationConj | RelationDisj','RelationDisj',3,'p_RelationDisj','parser.py',128),
  ('RelationConj -> ModRelation','RelationConj',1,'p_RelationConj','parser.py',142),
  ('RelationConj -> ModRelation RelationConj','RelationConj',2,'p_RelationConj','parser.py',143),
  ('RelationConj -> ModRelation & RelationConj','RelationConj',3,'p_RelationConj','parser.py',144),
  ('ModRelation -> RelChild','ModRelation',1,'p_ModRelation','parser.py',157),
  ('RelChild -> Relation','RelChild',1,'p_RelChild','parser.py',164),
  ('Relation -> RELATION { Attributes } Relation_Next','Relation',5,'p_Relation','parser.py',171),
  ('Relation_Next -> ModNode','Relation_Next',1,'p_Relation_Next','parser.py',182),
  ('Relation_Next -> ( SubNode )','Relation_Next',3,'p_Relation_Next','parser.py',183),
  ('ModNode -> Child','ModNode',1,'p_ModNode','parser.py',193),
  ('Child -> Description','Child',1,'p_Child','parser.py',200),
  ('Description -> { Attributes }','Description',3,'p_Description','parser.py',207),
  ('Description -> { Attributes } = IDENTIFIER','Description',5,'p_Description','parser.py',208),
  ('Attributes -> IDENTIFIER : REGEX','Attributes',3,'p_Attributes','parser.py',217),
  ('Attributes -> IDENTIFIER : REGEX , Attributes','Attributes',5,'p_Attributes','parser.py',218),
  ('Attributes -> empty','Attributes',1,'p_Attributes','parser.py',219),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',231),
]
